-- =============================================
-- SEQUENCES
-- =============================================
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE course_seq START WITH 1 INCREMENT BY 1;

-- =============================================
-- USERS TABLE
-- =============================================
CREATE TABLE users (
    id NUMBER DEFAULT user_seq.NEXTVAL PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(100),
    role VARCHAR2(20) DEFAULT 'student'
        CHECK (role IN ('student', 'instructor', 'admin')),
    avatar_url VARCHAR2(500),
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP
);

-- =============================================
-- COURSES TABLE
-- =============================================
CREATE TABLE courses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(1000),
    short_description VARCHAR2(200),
    duration_hours NUMBER(3),
    instructor_id NUMBER REFERENCES users(id),
    price NUMBER(8,2) DEFAULT 0,
    free_certificate NUMBER(1) DEFAULT 0
        CHECK (free_certificate IN (0,1)),
    course_level VARCHAR2(20) DEFAULT 'beginner'
        CHECK (course_level IN ('beginner', 'intermediate', 'advanced')),
    category VARCHAR2(50),
    thumbnail_url VARCHAR2(500),
    total_lessons NUMBER DEFAULT 0,
    rating NUMBER(3,2) DEFAULT 0,
    is_published NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================
-- ENROLLMENTS TABLE
-- =============================================
CREATE TABLE enrollments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id),
    course_id NUMBER REFERENCES courses(id),
    enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed NUMBER(1) DEFAULT 0
        CHECK (completed IN (0,1)),
    progress_percentage NUMBER(5,2) DEFAULT 0
        CHECK (progress_percentage BETWEEN 0 AND 100),
    completed_at TIMESTAMP,
    certificate_issued NUMBER(1) DEFAULT 0,
    UNIQUE (user_id, course_id)
);

-- =============================================
-- COURSE CERTIFICATES
-- =============================================
CREATE TABLE course_certificates (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER UNIQUE REFERENCES enrollments(id),
    certificate_number VARCHAR2(50) UNIQUE NOT NULL,
    certificate_url VARCHAR2(500),
    issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    verified NUMBER(1) DEFAULT 1
);

-- =============================================
-- COURSE REVIEWS
-- =============================================
CREATE TABLE course_reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id),
    course_id NUMBER REFERENCES courses(id),
    rating NUMBER(2)
        CHECK (rating BETWEEN 1 AND 5),
    review_text VARCHAR2(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, course_id)
);

-- =============================================
-- SAMPLE DATA
-- =============================================

-- USERS
INSERT INTO users (username, email, password_hash, full_name, role) VALUES
('john_doe', 'john@prephub.com', 'hashed123', 'John Doe', 'instructor'),
('jane_smith', 'jane@example.com', 'hashed456', 'Jane Smith', 'student'),
('admin_user', 'admin@prephub.com', 'adminpass', 'Admin User', 'admin'),
('student1', 'student1@test.com', 'pass789', 'Test Student', 'student');

-- COURSES
INSERT INTO courses (
    course_name, description, duration_hours,
    instructor_id, price, free_certificate,
    course_level, category
) VALUES
('React.js Fundamentals', 'Complete React beginner course with Hooks & Components', 12, 1, 0, 1, 'beginner', 'Frontend'),
('Node.js & Express API', 'Build production REST APIs with Node.js & Express', 10, 1, 0, 1, 'beginner', 'Backend'),
('Oracle SQL Masterclass', 'Complete SQL guide for Oracle Database', 15, 1, 0, 1, 'intermediate', 'Database'),
('Docker for Developers', 'Containerize your apps with Docker', 6, 1, 0, 1, 'beginner', 'DevOps'),
('Git & GitHub Mastery', 'Version control from beginner to pro', 8, 1, 0, 1, 'beginner', 'DevOps'),
('Advanced React Patterns', 'Redux, Context API, Performance Optimization', 18, 1, 79.99, 0, 'advanced', 'Frontend'),
('Fullstack MERN Stack', 'Complete e-commerce app with MongoDB, React, Node', 30, 1, 149.99, 0, 'advanced', 'Fullstack'),
('Jenkins CI/CD Pipeline', 'Production DevOps pipeline with Jenkins & SonarQube', 20, 1, 99.99, 0, 'intermediate', 'DevOps'),
('Microservices Architecture', 'Build scalable Node.js microservices', 25, 1, 129.99, 0, 'advanced', 'Backend'),
('Kubernetes Essentials', 'Deploy container apps with Kubernetes', 22, 1, 119.99, 0, 'advanced', 'DevOps');

-- ENROLLMENTS
INSERT INTO enrollments (user_id, course_id, progress_percentage, completed) VALUES
(2, 1, 100, 1),
(2, 2, 85, 0),
(2, 5, 100, 1);

-- CERTIFICATES
INSERT INTO course_certificates (enrollment_id, certificate_number, certificate_url) VALUES
(1, 'PREPHUB-2026-001', 'https://prephub.com/cert/react-jane001.pdf'),
(3, 'PREPHUB-2026-002', 'https://prephub.com/cert/git-jane002.pdf');

-- REVIEWS
INSERT INTO course_reviews (user_id, course_id, rating, review_text) VALUES
(2, 1, 5, 'Excellent React course! Got my free certificate!'),
(2, 2, 4, 'Great Node.js content, almost finished.');

COMMIT;

-- =============================================
-- PRODUCTION QUERIES
-- =============================================

-- 1. ALL COURSES WITH CERTIFICATE STATUS
SELECT
    c.id,
    c.course_name,
    c.duration_hours || ' hours' AS duration,
    c.price,
    CASE
        WHEN c.free_certificate = 1 THEN '✅ FREE CERTIFICATE'
        ELSE '💎 PREMIUM (' || c.price || ')'
    END AS certificate_status,
    c.course_level,
    c.rating || ' ⭐' AS rating
FROM courses c
ORDER BY c.id;

-- 2. USER DASHBOARD
SELECT
    u.username,
    c.course_name,
    e.progress_percentage || '%' AS progress,
    CASE
        WHEN cc.id IS NOT NULL THEN '🏆 CERTIFICATE ISSUED'
        WHEN c.free_certificate = 1 AND e.completed = 1 THEN '✅ READY TO CLAIM'
        WHEN e.completed = 1 THEN '💎 PREMIUM CERTIFICATE'
        ELSE 'In Progress'
    END AS status
FROM enrollments e
JOIN users u ON e.user_id = u.id
JOIN courses c ON e.course_id = c.id
LEFT JOIN course_certificates cc ON e.id = cc.enrollment_id
ORDER BY u.username, e.progress_percentage DESC;

-- 3. FREE COURSES
SELECT
    course_name,
    duration_hours,
    instructor_id
FROM courses
WHERE free_certificate = 1
  AND is_published = 1
ORDER BY rating DESC;

-- 4. TOP RATED COURSES
SELECT
    course_name,
    rating,
    CASE
        WHEN free_certificate = 1 THEN 'FREE CERT'
        ELSE 'PREMIUM'
    END AS type
FROM courses
ORDER BY rating DESC, price ASC;

-- 5. CERTIFICATE STATS
SELECT
    'Free Certificates Eligible' AS metric,
    COUNT(*) AS count
FROM courses
WHERE free_certificate = 1
UNION ALL
SELECT
    'Certificates Issued',
    COUNT(*)
FROM course_certificates;
